export const READY_STATUS_SCORE_THRESHOLD = 85;
export const ISSUE_FREE_SCORE_THRESHOLD = 80;
export const MEDIUM_ISSUE_SCORE_THRESHOLD = 70;
export const HIGH_ISSUE_SCORE_THRESHOLD = 55;
export const NEEDS_FIX_PROBABILITY_THRESHOLD = 0.5;
